### ISSUE TITLE
Match error when activating log adapters with enable()

### ISSUE THREAD

**Issue by danwild** [VeliovGroup/Meteor-logger#10]
Firstly - thanks for all your contributions! 👍  

Here's my issue; when initialising a new log adapter, like this:

```javascript
new LoggerConsole(log, myOptions).enable({
    server: true,
    filter: ['*']
});
```

I get the following error:

```
 Exception while invoking method '1_logger_emit_Console' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
I20180226-10:55:39.779(11)?     at check (packages/check/match.js:35:15)
I20180226-10:55:39.779(11)?     at MethodInvocation.method.(anonymous function) (packages/ostrio:logger/logger.js:175:9)
I20180226-10:55:39.779(11)?     at packages/check/match.js:108:16
I20180226-10:55:39.779(11)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180226-10:55:39.779(11)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
I20180226-10:55:39.779(11)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
I20180226-10:55:39.779(11)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180226-10:55:39.779(11)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180226-10:55:39.780(11)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180226-10:55:39.784(11)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180226-10:55:39.785(11)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180226-10:55:39.785(11)?     at new Promise (<anonymous>)
I20180226-10:55:39.785(11)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180226-10:55:39.785(11)?     at packages/ddp-server/livedata_server.js:559:43
I20180226-10:55:39.785(11)? Sanitized and reported to the client as: Match failed [400]

```

Looking closer at `packages/ostrio:logger/logger.js:175:9`, I notice that the `enable` param is not matched/optional?

So; if I change my init to include enable, this works:

```javascript
new LoggerConsole(log, myOptions).enable({
    enable: true,
    server: true,
    filter: ['*']
});
```
 
Perhaps this is by design. If so, might be nice to have this mentioned in the docs.
Otherwise, perhaps we just need to change the check to something like:

```javascript
check(options, {
      enable: Match.Optional(Boolean), // logger.js:171
      client: Match.Optional(Boolean),
      server: Match.Optional(Boolean),
      filter: Match.Optional([String])
    });
```

FYI my setup:

- ostrio:logger@2.0.6
- ostrio:loggerconsole@2.0.3
- ostrio:loggerfile@2.0.4
- Meteor 1.6.1

**Comment by danwild** [comment]
Hmm looking closer, the `enable` property is not related to the issue.

Oddly, it seems that if the `client` boolean does not equal `server` value (e.g. `{ client: true, server: false }`) , I do not get the above error... 

And, if both set to `true`, the Logger does actually initialise and logs a few lines of output successfully  before throwing the error.

I will dig a bit deeper.

Thanks.

**Comment by dr-dimitru** [comment]
@danwild not sure where you've got confused.
Take a look at our test cases - https://github.com/VeliovGroup/Meteor-logger/blob/master/logger-tests.js
Hopefully you could get there some inspiration :)
