### ISSUE TITLE
Match error when log data object is empty

### ISSUE THREAD

**Issue by danwild** [VeliovGroup/Meteor-logger#11]
### Log calls where `data` param is omitted, or is an empty object causes error:

```javascript
Exception while invoking method '1_logger_emit_Console' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
I20180226-10:55:39.779(11)?     at check (packages/check/match.js:35:15)
I20180226-10:55:39.779(11)?     at MethodInvocation.method.(anonymous function) (packages/ostrio:logger/logger.js:175:9)
I20180226-10:55:39.779(11)?     at packages/check/match.js:108:16
I20180226-10:55:39.779(11)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180226-10:55:39.779(11)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
I20180226-10:55:39.779(11)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
I20180226-10:55:39.779(11)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180226-10:55:39.779(11)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180226-10:55:39.780(11)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180226-10:55:39.784(11)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180226-10:55:39.785(11)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180226-10:55:39.785(11)?     at new Promise (<anonymous>)
I20180226-10:55:39.785(11)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180226-10:55:39.785(11)?     at packages/ddp-server/livedata_server.js:559:43
I20180226-10:55:39.785(11)? Sanitized and reported to the client as: Match failed [400]
```

If data param == `{}`  it evaluates to `false` when passed to the logger.
Likewise if data is param is not included, e.g. `log.info('data results')` it becomes falsey.

A `false` value is not currently a valid option in the check matches: 

logger.js:175: `check(data, Match.Optional(Match.OneOf(String, Object, null)));`

So for example; both of these calls fail, despite only omitting *optional* params:

```javascript
log.info('data results');
log.info('data results', {});
```

### Versions:
- ostrio:logger@2.0.6
- ostrio:loggerconsole@2.0.3
- ostrio:loggerfile@2.0.4
- Meteor 1.6.1

**Comment by danwild** [comment]
This was misdiagnosed, [PR has been closed](https://github.com/VeliovGroup/Meteor-logger/pull/12#issuecomment-368683232).
